id: IEA9AF4C9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:40:08+00:00'
last_modified: '2022-06-07T18:45:59.239478+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9256
  title: གནས་རྙིང་ཆོས་འབྱུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    312F:
      image_group_id: I1KG9338
      title: ''
      total_pages: 134
      order: 1
      base_file: 312F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
