id: P003270
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9256
  title: གནས་རྙིང་ཆོས་འབྱུང་།
  author: ''
  volumes:
    d7267d4ffe41424da1a203017efd1e1a:
      image_group_id: I1KG9338
      title: ''
      volume_number: 1
      total_pages: 134
      base_file: v001.txt
